### ISSUE TITLE
Invalid status code: 1 Error

### ISSUE THREAD

**Issue by iib0011** [Balastrong/chess-stats-action#5]
I have this when I try to run the action on a fork Invalid status code: 1
Error: Invalid status code: 1

**Comment by Balastrong** [comment]
Thanks for the report!
First of all, indeed it could show some more logs and information on why it fails.
Do you think you can give it a try? As you already have the fork, you can try locally to add some more logs :)

Speaking of local, does it run there for you? You can either do that by running the vscode debugger, or a simple `npm run test-debug` that will execute the test, running the action.

I'm sorry for the lack of documentation, it's still a fresh project but I will work on it!

**Comment by Balastrong** [comment]
I added a few more logging with a9e3c4e1ab5acaaad3b016f0df02de3dc54f9a4d

Can you please update your fork and try again to run the action manually? :)

**Comment by Balastrong** [comment]
I added a few more logging with https://github.com/Balastrong/chess-stats-action/commit/a9e3c4e1ab5acaaad3b016f0df02de3dc54f9a4d

@iib0011  can you please update your fork and try again to run the action manually? :)

**Comment by iib0011** [comment]
It works well in vscode but not in github

**Comment by iib0011** [comment]
still no logs 
![image](https://user-images.githubusercontent.com/58892076/181775272-fa3cdf97-1d51-4e1b-908b-a6b91da29a50.png)

**Comment by Balastrong** [comment]
Thanks :)

I did some investigation and looks like it fails on the `commitFile` function.
https://github.com/Balastrong/chess-stats-action/blob/a9e3c4e1ab5acaaad3b016f0df02de3dc54f9a4d/src/main.ts#L59

Feel free to open a PR if you can manage to fix it :)

**Comment by iib0011** [comment]
Okay

**Comment by Balastrong** [comment]
I've got some good news, a potential cause was that I changed the file name from hardcoded README.md to a new input passed via the env variables.
However, the commit action still had the hardcoded filename.

@iib0011 can you please update your fork now and let me know if it works?

**Comment by iib0011** [comment]
Okay. I'll check it

**Comment by iib0011** [comment]
It works now. Great
